/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request OTP for phone login */
        post: operations["request_otp_api_v1_auth_request_otp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify OTP and issue JWT tokens */
        post: operations["verify_otp_api_v1_auth_verify_otp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate JWT access + refresh tokens */
        post: operations["refresh_tokens_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and revoke refresh token */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete farmer onboarding with consent */
        post: operations["onboarding_api_v1_auth_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my profile */
        get: operations["get_profile_api_v1_me_get"];
        put?: never;
        post?: never;
        /**
         * Deactivate my account
         * @description Soft-delete: sets is_active=False and records timestamp.
         */
        delete: operations["delete_account_api_v1_me_delete"];
        options?: never;
        head?: never;
        /** Update my profile */
        patch: operations["update_profile_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/crop-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 1-tap crop status update */
        patch: operations["update_crop_status_api_v1_me_crop_status_patch"];
        trace?: never;
    };
    "/api/v1/advisories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List advisories for the current farmer's panchayat
         * @description Returns APPROVED advisories for the farmer's panchayat (most recent first).
         *     Includes a persistent `simulated_banner` flag when data_source=SIMULATED.
         */
        get: operations["list_advisories_api_v1_advisories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisories/{advisory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Advisory detail */
        get: operations["get_advisory_api_v1_advisories__advisory_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisories/{advisory_id}/translate/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** On-demand translation */
        get: operations["translate_advisory_endpoint_api_v1_advisories__advisory_id__translate__lang__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/officer/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending advisory approval queue
         * @description Returns PENDING advisories within the officer's jurisdiction.
         *     CRITICAL advisories appear first.
         */
        get: operations["approval_queue_api_v1_officer_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/officer/advisories/{advisory_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve an advisory */
        post: operations["approve_advisory_api_v1_officer_advisories__advisory_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/officer/advisories/{advisory_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject an advisory */
        post: operations["reject_advisory_api_v1_officer_advisories__advisory_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/officer/advisories/{advisory_id}/translate/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Translation preview */
        get: operations["translation_preview_api_v1_officer_advisories__advisory_id__translate__lang__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/officer/broadcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Broadcast approved advisories to farmers
         * @description Dispatch approved advisories to all farmers in the relevant panchayats.
         *
         *     Safety:
         *       - confirm=False → dry-run, returns what would be sent
         *       - SIMULATED advisories → BLOCKED_SIMULATED, never reach provider
         *       - Only officers with jurisdiction over the advisory's block may broadcast
         *       - Enforces farmer-level 72h cooldown (CRITICAL alerts bypass)
         *       - Enforces farmer consent / opt-out
         */
        post: operations["broadcast_advisories_api_v1_officer_broadcast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/officer/delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delivery status for recent notifications */
        get: operations["delivery_status_api_v1_officer_delivery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/twilio/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Twilio delivery status callback
         * @description Update NotificationLog.dispatch_status from Twilio's delivery callback.
         *
         *     Status mapping:
         *       sent      → SENT
         *       delivered → DELIVERED
         *       failed / undelivered → FAILED
         */
        post: operations["twilio_status_callback_api_v1_webhooks_twilio_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/tiles/blocks/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * MVT tiles for blocks (low zoom)
         * @description Generate Mapbox Vector Tile (MVT) for blocks at tile coordinate (z, x, y).
         *     Joins block_forecast_agg for fast rendering at low zoom levels (zoom 4 - 10).
         */
        get: operations["get_block_mvt_tile_api_v1_geo_tiles_blocks__z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/tiles/panchayats/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * MVT tiles for panchayats (high zoom)
         * @description Generate Mapbox Vector Tile (MVT) for Gram Panchayats at tile coordinate (z, x, y).
         *     Provides hyperlocal probability attributes for 3D extrusion at zoom 10 - 18.
         */
        get: operations["get_panchayat_mvt_tile_api_v1_geo_tiles_panchayats__z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/geojson/panchayats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GeoJSON FeatureCollection for panchayats (2D Fallback)
         * @description Returns GeoJSON FeatureCollection of panchayats with forecast properties.
         *     Used by ChoroplethMap2D fallback when WebGL is unavailable.
         */
        get: operations["get_panchayats_geojson_api_v1_geo_geojson_panchayats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search geography by query string
         * @description Search panchayats, blocks, and districts. Returns coordinates and hierarchy.
         */
        get: operations["search_geo_api_v1_geo_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Point-in-polygon lookup from lat/lon
         * @description Finds which panchayat, block, and district contains (lat, lon).
         */
        get: operations["point_in_polygon_lookup_api_v1_geo_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecasts/panchayat/{panchayat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 4-week probabilistic outlook for Panchayat
         * @description Returns weeks 1, 2, 3, 4 probabilistic outlook for a Gram Panchayat.
         *     Includes percentiles (p10, p50, p90), SHAP values, and data_source banner flag.
         */
        get: operations["get_panchayat_forecast_api_v1_forecasts_panchayat__panchayat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveBody */
        ApproveBody: {
            /** Notes */
            notes?: string | null;
        };
        /** Body_twilio_status_callback_api_v1_webhooks_twilio_status_post */
        Body_twilio_status_callback_api_v1_webhooks_twilio_status_post: {
            /** Messagesid */
            MessageSid?: string | null;
            /** Messagestatus */
            MessageStatus?: string | null;
            /** To */
            To?: string | null;
            /** From */
            From?: string | null;
        };
        /** BroadcastBody */
        BroadcastBody: {
            /** Advisory Ids */
            advisory_ids: number[];
            /**
             * Channel
             * @default SMS
             */
            channel: string;
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /** CropStatusPatchIn */
        CropStatusPatchIn: {
            /** Crop Status */
            crop_status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IrrigationSource
         * @enum {string}
         */
        IrrigationSource: "RAINFED" | "CANAL" | "BOREWELL_WELL" | "TANK_POND" | "DRIP_SPRINKLER" | "OTHER" | "BOREWELL" | "TANK";
        /** OnboardingIn */
        OnboardingIn: {
            /** Panchayat Id */
            panchayat_id?: number | null;
            /** Crop Type */
            crop_type?: string | null;
            irrigation_source?: components["schemas"]["IrrigationSource"] | null;
            /** Farm Size Acres */
            farm_size_acres?: number | null;
            /** Soil Type */
            soil_type?: string | null;
            /**
             * Consent
             * @default false
             */
            consent: boolean;
            /** Preferred Language */
            preferred_language?: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /** User Id */
            user_id: number;
            /** Phone Number */
            phone_number: string;
            /** Role */
            role: string;
            /** Preferred Language */
            preferred_language: string;
            /** Is Active */
            is_active: boolean;
            /** Consent Given At */
            consent_given_at: string | null;
            /** Panchayat Id */
            panchayat_id: number | null;
            /** Crop Type */
            crop_type: string | null;
            /** Crop Status */
            crop_status: string | null;
            /** Irrigation Source */
            irrigation_source: string | null;
            /** Farm Size Acres */
            farm_size_acres: number | null;
            /** Soil Type */
            soil_type: string | null;
        };
        /** ProfilePatchIn */
        ProfilePatchIn: {
            /** Preferred Language */
            preferred_language?: string | null;
            /** Panchayat Id */
            panchayat_id?: number | null;
            /** Crop Type */
            crop_type?: string | null;
            irrigation_source?: components["schemas"]["IrrigationSource"] | null;
            /** Farm Size Acres */
            farm_size_acres?: number | null;
            /** Soil Type */
            soil_type?: string | null;
        };
        /** RequestOTPIn */
        RequestOTPIn: {
            /** Phone Number */
            phone_number: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyOTPIn */
        VerifyOTPIn: {
            /** Phone Number */
            phone_number: string;
            /** Otp */
            otp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_otp_api_v1_auth_request_otp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestOTPIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_api_v1_auth_verify_otp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOTPIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_tokens_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    onboarding_api_v1_auth_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    delete_account_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    update_profile_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_crop_status_api_v1_me_crop_status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CropStatusPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_advisories_api_v1_advisories_get: {
        parameters: {
            query?: {
                lead_week?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_advisory_api_v1_advisories__advisory_id__get: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path: {
                advisory_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_advisory_endpoint_api_v1_advisories__advisory_id__translate__lang__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advisory_id: number;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approval_queue_api_v1_officer_queue_get: {
        parameters: {
            query?: {
                block_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_advisory_api_v1_officer_advisories__advisory_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advisory_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_advisory_api_v1_officer_advisories__advisory_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advisory_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translation_preview_api_v1_officer_advisories__advisory_id__translate__lang__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advisory_id: number;
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    broadcast_advisories_api_v1_officer_broadcast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BroadcastBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delivery_status_api_v1_officer_delivery_get: {
        parameters: {
            query?: {
                advisory_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    twilio_status_callback_api_v1_webhooks_twilio_status_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Twilio-Signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_twilio_status_callback_api_v1_webhooks_twilio_status_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_block_mvt_tile_api_v1_geo_tiles_blocks__z___x___y__pbf_get: {
        parameters: {
            query?: {
                lead_week?: number;
            };
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_panchayat_mvt_tile_api_v1_geo_tiles_panchayats__z___x___y__pbf_get: {
        parameters: {
            query?: {
                lead_week?: number;
            };
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_panchayats_geojson_api_v1_geo_geojson_panchayats_get: {
        parameters: {
            query?: {
                lead_week?: number;
                block_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_geo_api_v1_geo_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    point_in_polygon_lookup_api_v1_geo_lookup_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_panchayat_forecast_api_v1_forecasts_panchayat__panchayat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                panchayat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
